# Generated by Django 4.2.6 on 2023-11-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_livromodel_ano_livromodel_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.IntegerField(null=True, verbose_name='ISBN'),
        ),
    ]
