# Generated by Django 4.2.6 on 2023-11-02 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_livromodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='isbn',
            field=models.CharField(max_length=200, null=True, verbose_name='ISBN'),
        ),
    ]
