# Generated by Django 4.2.6 on 2023-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_livromodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='ano',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='livromodel',
            name='numero_paginas',
            field=models.IntegerField(null=True, verbose_name='Número de Páginas'),
        ),
    ]
