# Generated by Django 4.2.6 on 2023-11-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_livromodel_ano_alter_livromodel_numero_paginas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livromodel',
            name='ano',
            field=models.IntegerField(null=True, verbose_name='ano'),
        ),
    ]
